package model;
// Generated 22/08/2017 11:33:32 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Alertas generated by hbm2java
 */
public class Alertas  implements java.io.Serializable {


     private Long id;
     private Usuario usuario;
     private boolean leido;
     private String contenido;
     private Date fechaCreacion;
     private Date fechaLeido;

    public Alertas() {
    }

    public Alertas(Usuario usuario, boolean leido, String contenido, Date fechaCreacion, Date fechaLeido) {
       this.usuario = usuario;
       this.leido = leido;
       this.contenido = contenido;
       this.fechaCreacion = fechaCreacion;
       this.fechaLeido = fechaLeido;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public boolean isLeido() {
        return this.leido;
    }
    
    public void setLeido(boolean leido) {
        this.leido = leido;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaLeido() {
        return this.fechaLeido;
    }
    
    public void setFechaLeido(Date fechaLeido) {
        this.fechaLeido = fechaLeido;
    }




}


