package model;
// Generated 14/09/2017 04:33:27 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoActuador generated by hbm2java
 */
public class CatalogoActuador  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private String tipo;
     private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);

    public CatalogoActuador() {
    }

	
    public CatalogoActuador(String nombre, String tipo) {
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public CatalogoActuador(String nombre, String tipo, Set<Cultivo> cultivos) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.cultivos = cultivos;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Cultivo> getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set<Cultivo> cultivos) {
        this.cultivos = cultivos;
    }




}


