package model;
// Generated 22/08/2017 11:33:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private Long id;
     private Usuario usuario;
     private String ip;
     private String nombre;
     private float latitud;
     private float longitud;
     private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);
     private Set<Cultivo> cultivos_1 = new HashSet<Cultivo>(0);
     private Set<Estadistica> estadisticas = new HashSet<Estadistica>(0);

    public Estacion() {
    }

	
    public Estacion(Usuario usuario, String ip, String nombre, float latitud, float longitud) {
        this.usuario = usuario;
        this.ip = ip;
        this.nombre = nombre;
        this.latitud = latitud;
        this.longitud = longitud;
    }
    public Estacion(Usuario usuario, String ip, String nombre, float latitud, float longitud, Set<Cultivo> cultivos, Set<Cultivo> cultivos_1, Set<Estadistica> estadisticas) {
       this.usuario = usuario;
       this.ip = ip;
       this.nombre = nombre;
       this.latitud = latitud;
       this.longitud = longitud;
       this.cultivos = cultivos;
       this.cultivos_1 = cultivos_1;
       this.estadisticas = estadisticas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(float latitud) {
        this.latitud = latitud;
    }
    public float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(float longitud) {
        this.longitud = longitud;
    }
    public Set<Cultivo> getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set<Cultivo> cultivos) {
        this.cultivos = cultivos;
    }
    public Set<Cultivo> getCultivos_1() {
        return this.cultivos_1;
    }
    
    public void setCultivos_1(Set<Cultivo> cultivos_1) {
        this.cultivos_1 = cultivos_1;
    }
    public Set<Estadistica> getEstadisticas() {
        return this.estadisticas;
    }
    
    public void setEstadisticas(Set<Estadistica> estadisticas) {
        this.estadisticas = estadisticas;
    }




}


