package model;
// Generated 22/08/2017 11:33:32 PM by Hibernate Tools 3.6.0



/**
 * Estadistica generated by hbm2java
 */
public class Estadistica  implements java.io.Serializable {


     private Long id;
     private Cultivo cultivo;
     private Estacion estacion;
     private String ip;
     private int temperatura;
     private int humedad;

    public Estadistica() {
    }

    public Estadistica(Cultivo cultivo, Estacion estacion, String ip, int temperatura, int humedad) {
       this.cultivo = cultivo;
       this.estacion = estacion;
       this.ip = ip;
       this.temperatura = temperatura;
       this.humedad = humedad;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cultivo getCultivo() {
        return this.cultivo;
    }
    
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }
    public Estacion getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public int getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(int temperatura) {
        this.temperatura = temperatura;
    }
    public int getHumedad() {
        return this.humedad;
    }
    
    public void setHumedad(int humedad) {
        this.humedad = humedad;
    }




}


