package model;
// Generated 14/09/2017 04:33:27 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCultivo generated by hbm2java
 */
public class TipoCultivo  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private int humedadMin;
     private int humedadMax;
     private int temperaturaMin;
     private int temperaturaMax;
     private int periodoRiego;
     private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);
     private Set<Cultivo> cultivos_1 = new HashSet<Cultivo>(0);

    public TipoCultivo() {
    }

	
    public TipoCultivo(String nombre, int humedadMin, int humedadMax, int temperaturaMin, int temperaturaMax, int periodoRiego) {
        this.nombre = nombre;
        this.humedadMin = humedadMin;
        this.humedadMax = humedadMax;
        this.temperaturaMin = temperaturaMin;
        this.temperaturaMax = temperaturaMax;
        this.periodoRiego = periodoRiego;
    }
    public TipoCultivo(String nombre, int humedadMin, int humedadMax, int temperaturaMin, int temperaturaMax, int periodoRiego, Set<Cultivo> cultivos, Set<Cultivo> cultivos_1) {
       this.nombre = nombre;
       this.humedadMin = humedadMin;
       this.humedadMax = humedadMax;
       this.temperaturaMin = temperaturaMin;
       this.temperaturaMax = temperaturaMax;
       this.periodoRiego = periodoRiego;
       this.cultivos = cultivos;
       this.cultivos_1 = cultivos_1;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getHumedadMin() {
        return this.humedadMin;
    }
    
    public void setHumedadMin(int humedadMin) {
        this.humedadMin = humedadMin;
    }
    public int getHumedadMax() {
        return this.humedadMax;
    }
    
    public void setHumedadMax(int humedadMax) {
        this.humedadMax = humedadMax;
    }
    public int getTemperaturaMin() {
        return this.temperaturaMin;
    }
    
    public void setTemperaturaMin(int temperaturaMin) {
        this.temperaturaMin = temperaturaMin;
    }
    public int getTemperaturaMax() {
        return this.temperaturaMax;
    }
    
    public void setTemperaturaMax(int temperaturaMax) {
        this.temperaturaMax = temperaturaMax;
    }
    public int getPeriodoRiego() {
        return this.periodoRiego;
    }
    
    public void setPeriodoRiego(int periodoRiego) {
        this.periodoRiego = periodoRiego;
    }
    public Set<Cultivo> getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set<Cultivo> cultivos) {
        this.cultivos = cultivos;
    }
    public Set<Cultivo> getCultivos_1() {
        return this.cultivos_1;
    }
    
    public void setCultivos_1(Set<Cultivo> cultivos_1) {
        this.cultivos_1 = cultivos_1;
    }




}


