package model;
// Generated 22/08/2017 11:33:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long id;
     private String username;
     private String password;
     private String correo;
     private long celular;
     private String nombre;
     private String APaterno;
     private String AMaterno;
     private Set<Estacion> estacions = new HashSet<Estacion>(0);
     private Set<Alertas> alertases = new HashSet<Alertas>(0);
     private Set<Estacion> estacions_1 = new HashSet<Estacion>(0);

    public Usuario() {
    }

	
    public Usuario(String username, String password, String correo, long celular, String nombre, String APaterno, String AMaterno) {
        this.username = username;
        this.password = password;
        this.correo = correo;
        this.celular = celular;
        this.nombre = nombre;
        this.APaterno = APaterno;
        this.AMaterno = AMaterno;
    }
    public Usuario(String username, String password, String correo, long celular, String nombre, String APaterno, String AMaterno, Set<Estacion> estacions, Set<Alertas> alertases, Set<Estacion> estacions_1) {
       this.username = username;
       this.password = password;
       this.correo = correo;
       this.celular = celular;
       this.nombre = nombre;
       this.APaterno = APaterno;
       this.AMaterno = AMaterno;
       this.estacions = estacions;
       this.alertases = alertases;
       this.estacions_1 = estacions_1;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public long getCelular() {
        return this.celular;
    }
    
    public void setCelular(long celular) {
        this.celular = celular;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAPaterno() {
        return this.APaterno;
    }
    
    public void setAPaterno(String APaterno) {
        this.APaterno = APaterno;
    }
    public String getAMaterno() {
        return this.AMaterno;
    }
    
    public void setAMaterno(String AMaterno) {
        this.AMaterno = AMaterno;
    }
    public Set<Estacion> getEstacions() {
        return this.estacions;
    }
    
    public void setEstacions(Set<Estacion> estacions) {
        this.estacions = estacions;
    }
    public Set<Alertas> getAlertases() {
        return this.alertases;
    }
    
    public void setAlertases(Set<Alertas> alertases) {
        this.alertases = alertases;
    }
    public Set<Estacion> getEstacions_1() {
        return this.estacions_1;
    }
    
    public void setEstacions_1(Set<Estacion> estacions_1) {
        this.estacions_1 = estacions_1;
    }




}


