package model;
// Generated 14/09/2017 04:33:27 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long id;
     private String username;
     private String password;
     private String correo;
     private long celular;
     private String nombre;
     private String paterno;
     private String materno;
     private Set<Estacion> estacions = new HashSet<Estacion>(0);     

    public Usuario() {
    }

    public Usuario(Long id) {
        this.id = id;
    }
    
    public Usuario(String username, String password, String correo, long celular, String nombre, String paterno, String materno) {
        this.username = username;
        this.password = password;
        this.correo = correo;
        this.celular = celular;
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
    }
    public Usuario(String username, String password, String correo, long celular, String nombre, String paterno, String materno, Set<Estacion> estacions) {
       this.username = username;
       this.password = password;
       this.correo = correo;
       this.celular = celular;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.estacions = estacions;       
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public long getCelular() {
        return this.celular;
    }
    
    public void setCelular(long celular) {
        this.celular = celular;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public Set<Estacion> getEstacions() {
        return this.estacions;
    }
    
    public void setEstacions(Set<Estacion> estacions) {
        this.estacions = estacions;
    }    
}


